Define an exception named OutOfRangeError. Write a function named name_the_number that asks the user for an integer, and if it's equal to 1, prints "one"; if it's equal to 2, prints "two", and if it's equal to 3, prints "three". If the the parameter is not one of those three values, the function should raise an OutOfRangeError. Write code that calls name_the_number in a try block, and handles the possible OutOfRangeError in an except block. It should handle an OutOfRangeError by printing "That's not one of the allowed values!"